name: GCP WIF authentication
run-name: ${{ github.actor }} triggered the deployment

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      id-token: write # This is required for requesting the JWT
      contents: read  # This is required for actions/checkout


    steps:
      - id: 'auth'
        name: 'Authenticate to GCP'
        uses: 'google-github-actions/auth@v0.3.1'
        with:
          create_credentials_file: 'true' 
          workload_identity_provider: '${{ secrets.WIF_PROVIDER }}'
          service_account: '${{ secrets.SA_EMAIL }}'
  
      - id: 'gcloud'
        name: 'gcloud'
        run: |-
          gcloud auth login
          gcloud services list
