name: List services in GCP
on:
  workflow_dispatch:

permissions:
  id-token: write
env:
  PROJECT_ID: '${{ secrets.}}'

jobs:
  Get_OIDC_ID_token:
    runs-on: ubuntu-latest
    steps:
    - id: 'auth'
      name: 'Authenticate to GCP'
      uses: 'google-github-actions/auth@v0.3.1'
      with:
          create_credentials_file: 'true'
          workload_identity_provider: 'projects/204905498895/locations/global/workloadIdentityPools/my-pool/providers/github'
          service_account: 'data-pipeline@burner-sidsoni1.iam.gserviceaccount.com'
    - id: 'gcloud'
      name: 'gcloud'
      run: |-
        gcloud auth login --brief --cred-file="${{ steps.auth.outputs.credentials_file_path }}"
        gcloud services list --project cloudquicklab
