name: Hello World Workflow with GCP Bucket Creation
run-name: ${{ github.actor }} triggered the deployment

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: 'read'
      id-token: 'write'

    steps:
      - id: 'Google auth'
        uses: 'google-github-actions/auth@v2'
        with:
          workload_identity_provider: '${{ secrets.WIF_PROVIDER }}'
          service_account: '${{ secrets.SA_EMAIL }}'
  
      - name: 'Use gcloud CLI'
        run: 'gcloud info'
